package com.hackthon.bo;

public enum ConversationStatus {

  INIT,READY_TO_CHANGE, CONFIRM_CHANGE, DUE_DATE_ERROR, CALLBACK_REQUESTED, CALLBACK_SHEDULED, EXIT, CHANGE_COMPLETED, CALLBACK_DATE_ERROR,

}
